(eval-after-load "yasnippet" '(diminish 'yas-minor-mode " Y"))
(eval-after-load "Undo-Tree" '(diminish 'undo-tree-mode))
(eval-after-load "abbrev" '(diminish 'abbrev-mode "Ab"))
(eval-after-load "autopair" '(diminish 'autopair-mode))
(eval-after-load "magit" '(diminish 'magit-auto-revert-mode))
